name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    steps:
    
    - name: Lint
      run: flake8 addon/globalPlugins/readFeeds/__init__.py
    